### ISSUE TITLE
Option to download from list

### ISSUE THREAD

**Issue by bandicootdancing** [pikami/tiktok-dl#1]
It would be nice if there was a command line option to download a list of users from a file.

**Comment by pikami** [comment]
Thanks for the suggestion.
Improvement added by commit: https://github.com/pikami/tiktok-dl/commit/6f8ab8a2779101244c0ee0f4c0957b5e0ac17651
This feature is available from version v1.3 https://github.com/pikami/tiktok-dl/releases/tag/1.3
