### ISSUE TITLE
Passing multiple arguments

### ISSUE THREAD

**Issue by rabea98** [pikami/tiktok-dl#15]
Hi,
I can't seem to pass multiple arguments to the script
example:
>tiktok-dl-master.exe -metadata -archive sophia.ilysm

only works with one option:
>>tiktok-dl-master.exe -metadata sophia.ilysm

**Comment by pikami** [comment]
Hello, the `-archive` flag needs to be given a value.
Here's an example:
`tiktok-dl-master.exe -metadata -archive archived_list.txt sophia.ilysm`
