### ISSUE TITLE
Not able to download tiktok generated usernames

### ISSUE THREAD

**Issue by bandicootdancing** [pikami/tiktok-dl#16]
Tiktok-dl doesn't appear to grab usernames generated by tiktok. @30463788129 is an example. I can find the account online but it turns into a long string. ``https://www.tiktok.com/@MS4wLjABAAAAb1x2kDqMT6XWon1R93XAAfbpFzCd6e5E6STC-JDksrrTMatNy7-EH6YK5Y_sfT9q``

Creating a share URL in the tiktok app doesn't appear to work with tiktok-dl either.

**Comment by pikami** [comment]
Hi, thanks for reporting this issue.
I don't know how to get to the user's profile by only knowing their account ID so if you know a way that would be really helpful.
As for now, the newest release supports the tiktok share URL, if it doesn't please share a sample share URL that doesn't work.
That long URL (`https://www.tiktok.com/@MS4wLjABAAAAb1x2kDqMT...`) should work fine with the current implementation.
