### ISSUE TITLE
[enchancment] outoput failed downloads to a log file

### ISSUE THREAD

**Issue by rabea98** [pikami/tiktok-dl#17]
Hi,
please make the script output usernames of failed downloads to a separate log file.

**Comment by pikami** [comment]
Requested feature was added and will be available on next release.
You can find pre-release builds here: https://github.com/pikami/tiktok-dl/actions
You can use this feature by passing the `-fail-log some_file` flag.

**Comment by rabea98** [comment]
Thanks !
