### ISSUE TITLE
Issue 5 still persists; not skipping user that doesn't exist

### ISSUE THREAD

**Issue by DankMemeGuy** [pikami/tiktok-dl#19]
When downloading from a list, it said "failed to get user uploads" then stops. It doesn't continue to the next user in the list. It also doesn't say which user so I can remove it from the list manually

#5

**Comment by pikami** [comment]
I wasn't able to reproduce the issue.
Could you make sure you're running the latest build from https://github.com/pikami/tiktok-dl/releases/tag/1.9.1
If you are running the latest build and it still doesn't work, please reply with:

- Full command that you are using to run the tool
- Any bulk download files
- Chrome version that you have currently installed
- Full output of the tool

Thank you.

**Comment by DankMemeGuy** [comment]
Latest changes fixed whatever was causing it! Thank you for your hard work @pikami it is very appreciated!
