### ISSUE TITLE
Download from music

### ISSUE THREAD

**Issue by senpai28** [pikami/tiktok-dl#2]
Can you add a features for downloading all videos under specified topics (challenge) or music?

For example: tiktok.com/music/xxxxxxxx

**Comment by paisenpoi** [comment]
Btw, thanks 🙏

**Comment by pikami** [comment]
Thanks for the suggestion.
Improvement added by commit: https://github.com/pikami/tiktok-dl/commit/884f9040dbf1fd2b53c37e4d2d5b76f2fb4a2a1f
This feature is available from version v1.4.1 https://github.com/pikami/tiktok-dl/releases/tag/1.4.1

**Comment by paisenpoi** [comment]
Very very thanks bro :))
