### ISSUE TITLE
Stuck at preloading

### ISSUE THREAD

**Issue by werid** [pikami/tiktok-dl#20]
I've noticed that sometimes the tool gets stuck at "Preloading...", but it was fairly rare. 

Yesterday, I started getting that all the time. Tried two different machines, two different ip's. Nothing gets past "Preloading..." 

Tiktok changed something or what could be the problem?

**Comment by DankMemeGuy** [comment]
How do you know it was two different IPs? If you're under a router you'd have the same IP.

Double check your IPs are actually different, also try a VPN.

**Comment by alecaputo13** [comment]
I'm facing this issue too. I'm on Windows

**Comment by DankMemeGuy** [comment]
Just confirmed on my end too. looks like it's down

**Comment by pikami** [comment]
Issue is fixed with version https://github.com/pikami/tiktok-dl/releases/tag/1.9.1
Please verify that it works and close the issue

**Comment by werid** [comment]
it works again for me, thanks.

**Comment by liner601** [comment]
This Issue has continued to persist, I updated and it worked for a bit but it stopped working a few hours ago.

Steps to replicate:
1. cd "Filepath"
2. tiktok-dl [-archive -metadata] "Username"
3. preloading..

Edit: Application version 1.9.1 Chrome version 80.0.3987.163

**Comment by pikami** [comment]
@liner601 Just tested, works for me, could you test it using another username to see if it works?
I just tested using the user `@poki` and it worked on my end.

**Comment by liner601** [comment]
> @liner601 Just tested, works for me, could you test it using another username to see if it works?
> I just tested using the user `@poki` and it worked on my end.

Chrome update seems to have fixed it, version 80.0.3987.163 seems to not work with the application.
