### ISSUE TITLE
Extracting users from a list

### ISSUE THREAD

**Issue by DankMemeGuy** [pikami/tiktok-dl#23]
Hello @pikami,

I'm not sure how else to contact you since your website doesn't have email and GitHub doesn't have messaging. 

I am wondering if it would be possible if you could create a seperate tool than Tiktok-dl that can export the list of users from a page. For example: 

- https://www.tiktok.com/tag/workdistractions?
- https://www.tiktok.com/music/original-sound-6737424213700889349

**Comment by pikami** [comment]
If you know how to code, you can use the `-json` flag on tiktok-dl, it will not download anything, just output scraped information in json format, then you could just code something up to extract what you need.
If you want to contact me feel free to write an email to pkpjuklas {at} gmail
