### ISSUE TITLE
Error: encountered exception 'Uncaught' (111:24)

### ISSUE THREAD

**Issue by ProvocativeCheese** [pikami/tiktok-dl#26]
I have not had this problem before. I tried reinstalling everything, but it did not help

When I try to download a link like this:
`./tiktok-dl -output /media/videos Downloaded https://www.tiktok.com/@vbadest_beauty/video/6808887309245730054`

I get the following:
`Error: encountered exception 'Uncaught' (111:24)`
`failed when scraping item: https://www.tiktok.com/@vbadest_beauty/video/6808887309245730054`

**Comment by pikami** [comment]
I couldn't reproduce your issue, could you update google chrome to the latest version and try again?

**Comment by ProvocativeCheese** [comment]
Now it works fine, thank you!
