### ISSUE TITLE
Release 2.0.0 windows not exe?

### ISSUE THREAD

**Issue by AlphaSlayer1964** [pikami/tiktok-dl#29]
In the 2.0.0 release the tiktok-dl file has not extension type and doesn't run with cmd. Is it supposed to be this way?

**Comment by giorgioarmani1** [comment]
I renamed it to .exe for both files which worked until today where I got stuck on preloading

**Comment by AlphaSlayer1964** [comment]
That worked sadly I also have the preloading problem on all versions now.
