### ISSUE TITLE
Customize deadline

### ISSUE THREAD

**Issue by lunarcontrol** [pikami/tiktok-dl#3]
First of all, This tool is amazing!

Would it be possible to add a custom command line parameter to customize the "context deadline." When I try to download an enormous music list the chrome step takes too long and it quits.

Here is the command I was using:
tiktok-dl.exe -metadata -debug https://www.tiktok.com/music/Snap-Em-Up-6623965005760957190

The output:
2020/01/29 15:01:33 context deadline exceeded /music/Snap-Em-Up-6623965005760957190

Maybe add a parameter like `-deadline <seconds> ` so we can download these massive music links.

Thanks!

**Comment by pikami** [comment]
Thanks for the suggestion.
Improvement added by commit: https://github.com/pikami/tiktok-dl/commit/673bbe1340983c56e4c911a812a71cebf14182d0
This feature is available from version v1.5 https://github.com/pikami/tiktok-dl/releases/tag/1.5
