### ISSUE TITLE
Latest version and the version right before it is stuck on Preloading

### ISSUE THREAD

**Issue by giorgioarmani1** [pikami/tiktok-dl#30]
Hey I ran into a bit of a problem today. I tried download by using username until it kept getting stuck on Preloading. It was working last night but now is having troubles. I tried using a vpn, a previous version, and also testing different usernames. Thanks and hope you can fix it. 

P.S sorry this is sort of a duplicate issue but It was working perfectly yesterday and now it doesn't, was just wondering if something is wrong.

**Comment by AlphaSlayer1964** [comment]
Same problem here just says preloading..... until it gives:
Preloading...Failed to get user uploads: context deadline exceeded

**Comment by werid** [comment]
the tool is working fine for me right now. 

if you hammer the tiktok servers with too many requests in a short amount of time, the tool will start to give this error. wait some hours or a day, and it will start working again.

**Comment by AlphaSlayer1964** [comment]
Is it possible to have a delay between searches then? That would be useful.

**Comment by xd003** [comment]
Same issue .. its simply stuck at preloading

**Comment by xd003** [comment]
> the tool is working fine for me right now.
> 
> if you hammer the tiktok servers with too many requests in a short amount of time, the tool will start to give this error. wait some hours or a day, and it will start working again.

Dude i used this thing for first time today still got stuck at preloading , it think it may have something to do with the executable itself

**Comment by pikami** [comment]
You can continue discussions on https://github.com/pikami/tiktok-dl/issues/32
