### ISSUE TITLE
Bulk download doesn't work

### ISSUE THREAD

**Issue by DankMemeGuy** [pikami/tiktok-dl#4]
It just says preloading but then timesout after 11 minutes.

Windows64

**Comment by pikami** [comment]
@DankMemeGuy I wasn't able to reproduce the issue.
Could you make sure you're running the latest build from https://github.com/pikami/tiktok-dl/releases/tag/1.6
If you are running the latest build and it still doesn't work, please reply with:
* Bulk download file that you are using
* Any command line flags that you are using
* Chrome version that you have currently installed

Thank you.

**Comment by DankMemeGuy** [comment]
80.0.3987.106

tiktok-dl [OPTIONS] -batch-file O:\tiktok\users.txt

the text file itself just contains two users:
bazziofficial
jakerokop

**Comment by pikami** [comment]
You should be running the tool like this: `tiktok-dl -batch-file O:\tiktok\users.txt`
The `[OPTIONS]` part is left for any optional flags you want to set while running the application and the string itself shouldn't be passed while running the tool.
Thanks for letting me know how the documentation might me misinterpreted, I'll need to update it.

**Comment by DankMemeGuy** [comment]
Ahh Works now! Thank you!!
