### ISSUE TITLE
Skippimg a user that doesn't exist in bulk

### ISSUE THREAD

**Issue by DankMemeGuy** [pikami/tiktok-dl#5]
The script will lag upon "preloading..." when the user isn't found (deleted, etc). I've tried setting a deadline of 60 seconds but then it just quits the entire script instead of continuing to the next user/line

**Comment by pikami** [comment]
Thanks for the bug report.
Bug fixed by commit: https://github.com/pikami/tiktok-dl/commit/7a691ad32d06d7c057656f2951b9dbe48e4a4191
This feature is available from version v1.7: https://github.com/pikami/tiktok-dl/releases/tag/1.7
