### ISSUE TITLE
Skip previously downloaded videos?

### ISSUE THREAD

**Issue by werid** [pikami/tiktok-dl#7]
Hi

a tiny feature request: would it be hard to add a download-archive file, so it can skip previously downloaded videos? 

i run it on a server, but i store the videos elsewhere afterwards.

**Comment by pikami** [comment]
Implementation acceptance criteria:
* Add a flag `-download-archive=someFileName.txt`
* After every video download append the video id to the given file
* Check the if the video id is in the file before downloading video

**Comment by pikami** [comment]
Thanks for your suggestion.
Feature has been implemented and will be available from release 1.9 and up.
If you don't want to wait for the release, you can download this development build: https://github.com/pikami/tiktok-dl/actions/runs/60489782
