### ISSUE TITLE
Does the limit flag work ?

### ISSUE THREAD

**Issue by Valued17** [pikami/tiktok-dl#9]
First off, Thanks a lot for the wonderful tool. Been using a lot since last 2 days.

I am unable to use the -limit flag. Below is my example and it doesnt work.

tiktok-dl -limit 5 tiktokusername

And it doesnt limit to 5 videos, actually doesnt work and gives error - **flag provided but not defined: -limit**

P.S - Also, does this download videos in the highest available resolution possible ?

Thanks again

**Comment by sashkop** [comment]
Hello @Valued17 

Did you run `go build` after repository pull?

**Comment by pikami** [comment]
This feature is not present in the current release, you can download a pre-release version here: https://github.com/pikami/tiktok-dl/actions/runs/45088239

**Comment by Valued17** [comment]
> Hello @Valued17
> 
> Did you run `go build` after repository pull?

I just downloaded from this link - https://github.com/pikami/tiktok-dl/releases/download/1.7/tiktok-dl_win64.zip and run it.

**Comment by Valued17** [comment]
> This feature is not present in the current release, you can download a pre-release version here: https://github.com/pikami/tiktok-dl/actions/runs/45088239

This version works with -limit flag. Thank you so much. 

**Also, does this download videos in the highest available resolution possible ?**

Thanks again

**Comment by pikami** [comment]
>Also, does this download videos in the highest available resolution possible ?

Yes, it does.

**Comment by Valued17** [comment]
> > Also, does this download videos in the highest available resolution possible ?
> 
> Yes, it does.

You Sir, are a beauty!!

**Comment by Valued17** [comment]
Oh, by the way, can the watermark be removed somehow or may be at a later stage ?
